### ISSUE TITLE
Mentorship Program cohort #2 announcement

### ISSUE THREAD

**Issue by naokomc** [WordPress/wp-contributor-working-group-tracker#6]
- [x] Prepare a mentee application form.
- [x] Prepare a mentor application form.
- [x] Draft a post for Community Team P2.
- [x] Make an [amplification request to Marketing Team](https://github.com/WordPress/Marketing-Team/issues/new?assignees=bjmcsherry%2Ceidolonnight%2Csereedmedia%2Crobinwpdeveloper&labels=amplification-request&projects=&template=request-for-amplification-template.yml&title=%5BAMPLIFY%5D%3A+)
- [x] Publish the post on Community Team P2.
- [x]  Link the P2 post from the [Contributor Working Group handbook page](https://make.wordpress.org/community/handbook/contributor-day/contributor-working-group/contributor-mentorship-program-for-wordpress/).
- [x] Send email to cohort 1 applicants who were not accepted

**Comment by naokomc** [comment]
Review wanted:

Mentee form draft:
https://airtable.com/appvqnikVPSLYjCyw/shryocM9MBvZLjja5

Mentor form draft:
~~https://airtable.com/appvqnikVPSLYjCyw/shrPj93dKbGsxTKs2~~
https://airtable.com/app6T93TnZmv7FCFT/shrKYTceK1yixRv3N

The Airtable account is accessible via 1Password (Deputies' vault/WPCS email).

**Comment by naokomc** [comment]
Community P2 announcement post draft:
[https://docs.google.com/document/d/1UNQgnxnDOk-kJYiUAmGEUwMdmL0Q87xAHvSJn4gozgk/edit](https://docs.google.com/document/d/1UNQgnxnDOk-kJYiUAmGEUwMdmL0Q87xAHvSJn4gozgk/edit)

Please review and leave a comment or use the suggest mode to edit.

**Comment by naokomc** [comment]
Made an amplification request to the Marketing Team: https://github.com/WordPress/Marketing-Team/issues/340

**Comment by naokomc** [comment]
P2 post published:
https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/

Updated these handbook pages:
https://make.wordpress.org/community/handbook/contributor-day/contributor-working-group/contributor-mentorship-program-for-wordpress/

https://make.wordpress.org/community/handbook/contributor-day/contributor-working-group/contributor-mentorship-program-for-wordpress/contributor-mentorship-program-cohorts/

**Comment by naokomc** [comment]
@yoga1103 kindly accepted the additional task to email cohort 1 applicants. He is now working on an email template.

**Comment by yoga1103** [comment]
Email template for a follow up with the cohort 1 applicants [rejected]: https://docs.google.com/document/d/1LJwp9AMVc4FSY0kHZp4U9fDIoidwGjv4bEQ9FLqcVFM/edit?usp=sharing

**Comment by yoga1103** [comment]
email sent to 34 cohort 1 applicants.
