### ISSUE TITLE
Schedule and conduct onboarding sessions

### ISSUE THREAD

**Issue by naokomc** [WordPress/wp-contributor-working-group-tracker#8]
Examples of past onboarding session videos:
[https://wordpress.tv/event/wordpress-contributor-mentorship-program/](https://wordpress.tv/event/wordpress-contributor-mentorship-program/)

Based on the feedback from Cohort 1, these are potential sessions.
Because of the timezone differences, attendance is 100% optional, and we will record everything.

- Welcome (Mentorship Program Kickoff)
- Mentor orientation - Mentors
- GitHub Basics
- Introduction to the WordPress Open Source Project - New contributors ([Slides available](https://docs.google.com/presentation/d/1vMSnanAW38SV07X7QxxNvSHaSMQZELdze5CDs7dRGdA/edit#slide=id.p))
- Introduction to the WordPress Project - New contributors
- Diversity and Inclusion in WordPress
- Team-specific onboarding session
- WordPress Playground

We will need volunteers to:

- [ ] Host sessions
- [ ] Add to shared Google Calendar & invite mentees
- [ ] Publish & share the recording with all mentees

**Comment by patriciabt** [comment]
I will ask in all teams a short video (max 10 minutes) to present their teams, what they do and how they do it.
How to start with that team.
Then for proper and longer videos, it will be done by interest and presence of mentors in the mentorship program (cohort 2) with the ultimate goal to have all teams having their onboarding process on video, also using already exisiting ones and evaluating if updates are necessary.
